### ISSUE TITLE
Error message: "Both PAKs have to be from same level!" in error only on PAKs created recently

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#3]
![image](https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/assets/51859157/c4c34ae1-0e15-4034-be28-37fd02166caa)

I started seeing this today only on commands.paks edited recently.

I tried comparing a file made in early September and it worked fine.  
But when I tried one from Sept 29th it failed with same error.

Matt Filer has been updating Commands Editor and CathodeLib. 
Maybe there's some 'under the hood' change that is causing this.

**Comment by Oliver2Goetz** [comment]
Thanks for reporting.
The reason the problem appeared was most likely a change in the OpenCAGE saving mechanism. I'll let Matt know about it. He can best say if this is an intended behaviour.

**Comment by ghramsey** [comment]
Thanks.  That change fixed it!

**Comment by Oliver2Goetz** [comment]
for documentation:

OpenCAGE saves the entrypoint composites like this:
before: P:\\CONTENT\\BUILD\\LEVELS\\PRODUCTION\\ENG_TOWPLATFORM
after: ENG_TOWPLATFORM
