### ISSUE TITLE
ENUM value is not shown

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#5]
![image](https://github.com/user-attachments/assets/14fd1831-21ef-4d74-8ecf-4be9c44d6287)

Just noticed this.  When showing an ENUM parameter it shows the 'EnumIndex' and 'EnumID' but the data passed on to
this ENUM as a text field is not shown.

For example the this ENUM entity name is UsableByCharacterClasses, the 'enumindex' is CHARACTER_CLASS_COMBINATION, 
and 'enumID' both show the same.  (Is that right?)  
![image](https://github.com/user-attachments/assets/7007b0c7-436c-4176-b43f-186279178f00)

As you can see there's a text field with value 1023 which is not being shown up in either tree or list view mode.

This is pretty minor but it would be a nice feature to have working in the future.

*edit*  OH. This is in the TECH_COMMS map if that makes any difference for your testings. *end edit*

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey ,
as far as I can see 1023 is not a valid enumIndex at for this ENUM.
Thus displaying as it is now will be the correct behaviour:
![image](https://github.com/user-attachments/assets/4d644321-1c63-45e8-931f-16233dc396f4)

Though I checked the other case in which the enumIndex can be valid. For CHARACTER_CLASS_COMBINATION there are 20 different ENUM values to select from. The numbers 0 - 19 are the enumIndexes/keys and on the right side of this screenshot you can see the values:
![image](https://github.com/user-attachments/assets/2d892a47-35ef-4815-9057-bf2991768ace)

For my local version I corrected it as follows while displaying the ENUM id, the display name and the respective index the user set it to:
![image](https://github.com/user-attachments/assets/15a8b55e-eaf9-4318-9d36-7b3781c8c84b)

Is this like you imagine it should look like?
If yes, I can happily release a new version tomorrow with the fix :)

**Comment by Oliver2Goetz** [comment]
And yeah, to add to my last comment.
I changed the formatting a bit to show a bit less text but making it clear what the value is supposed to mean.

**Comment by Oliver2Goetz** [comment]
For documentative purposes a view of changing a parameter of type ENUM:
![image](https://github.com/user-attachments/assets/21ad8672-8aeb-470c-9f7a-965aeec9aaf2)

**Comment by ghramsey** [comment]
That looks great!   Thank you and that was fast work!

Those character class combination enums are bitwise.  Not strictly 0-19, but you add together to achieve 
a combination which in case of a door for example can barr some characters' entry and permit others.

Matt Filer explained it to me once when I was noticing the numbers did not add up as expected.
He said he had not yet deciphered all of them at that time.

No matter. It's showing the value correctly.  Thank you again.

**Comment by Oliver2Goetz** [comment]
Hey @ghramsey, thanks for the information. I wasn't aware of that.

I just released a new version v7.0. You can read about the release notes here: https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/releases/tag/v0.7

This issue in included in there.
Also there should be another thing in there which might be in interest for you :)
