### ISSUE TITLE
New export function: output missing parameter name on modified entity

### ISSUE THREAD

**Issue by ghramsey** [Oliver2Goetz/AIPAKFileDifferentiation#6]
The export function is great!   I know I'd asked for that ages ago, but never thought it would be possible.
I wish Matt Filer would add something like that to his CathodeLib.DLL natively which would make this easier.

Looks like someething is amiss in how it's exporting.

Here's the program window and the text output.
![image](https://github.com/user-attachments/assets/9b225edf-19d6-4e5e-8886-fc2e6715eb73)

AYZ\LEVELS\SEVESTAPOL\TECHNICAL\LOBBY\TECHSUPPORT\TECH_SUPPORT (MODIFIED)
[MODIFIED] Door_Med_Blackbox {BOOL=False MODIFIED} | {BOOL=False CREATED} | {FLOAT=1 CREATED} | {FLOAT=1 CREATED} | {FLOAT=1 CREATED} | {BOOL=True CREATED} | {BOOL=False CREATED}
[MODIFIED] Door_Brace_1 {TRANSFORM=(29.9918, 14.2516, -10.4841), (-8.577981E-07, 180, 1.072251E-07) MODIFIED}
[MODIFIED] Door_SML_SCI_1 {BOOL=True MODIFIED}
[MODIFIED] VentTraversalMarker_1 {BOOL=True CREATED} | {FLOAT=1 CREATED}
[MODIFIED] VentTraversalMarker_3 {BOOL=True CREATED} | {FLOAT=1 CREATED}
[MODIFIED] VentTraversalMarker_12 {BOOL=True CREATED} | {FLOAT=1 CREATED}
[MODIFIED] VentTraversalMarker_13 {BOOL=True CREATED} | {FLOAT=1 CREATED}
[MODIFIED] VentTraversalMarker_9 {BOOL=True CREATED} | {FLOAT=1 CREATED}

[AIPakDiff-Export TECH_HUB 2024-08-10_8-11-04.txt](https://github.com/user-attachments/files/16569657/AIPakDiff-Export.TECH_HUB.2024-08-10_8-11-04.txt)

I added the text from the file too, but the entire file is attached.

Looks like it's got the entity name OK but the parameter modfied is not there.

So the output for ` [MODIFIED] Door_Med_Blackbox {BOOL=False MODIFIED}  |  {BOOL=False CREATED}  |  
{FLOAT=1 CREATED} | {FLOAT=1 CREATED}  | {FLOAT=1 CREATED}  | {BOOL=True CREATED}  |  {BOOL=False CREATED} `

Each parameter should have a name:

` [MODIFIED] Door_Med_Blackbox {lock_on_reset BOOL=False MODIFIED}|{can_be_powered BOOL=False CREATED}|
 {IsLocked FLOAT=1 CREATED} | {locked FLOAT=1 CREATED} |  {switch_off FLOAT=1 CREATED} |  {force_close_on_reset BOOL=True CREATED} |  {open_on-reset BOOL=False CREATED} `

**Comment by Oliver2Goetz** [comment]
Hey ramsey,

thank you a lot for taking a look at it this fast and sorry for the inconveniences.
This was sadly one of the last modifications I did to the export and it didn't catch my eyes in my last few tests before release.

I just released a new version with a fix included: https://github.com/Oliver2Goetz/AIPAKFileDifferentiation/releases/tag/v0.7.1
If there are other thing which could be a bug or even a small change request gladly let me know.

Thanks again and Happy Modding :)
